[build]
  command = "cd frontend/expense-tracker && npm install && npm run build"
  publish = "frontend/expense-tracker/dist"
  functions = "netlify/functions"

[dev]
  command = "cd frontend/expense-tracker && npm run dev"
  targetPort = 5173
  publish = "frontend/expense-tracker/dist"

[functions]
  node_bundler = "esbuild"

[[edge_functions]]
  function = "basicAuth"
  path = "/*"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
